# The version of the docker-compose.
version: "3.8"
# Telling docker-compose to build the client and server images and run them in containers.
services:
  client:
    # Telling docker-compose to build the client image using the Dockerfile in the client directory.
    build: ./front-end
    # Giving the container a name.
    container_name: front_end_C
    # Mapping the port 3000 on the host machine to the port 3000 on the container.
    ports:
      - "3000:3000"
    # Mapping the client directory on the host machine to the /app directory on the container.
    # volumes:
    #   - ./client:/app
    #   - ./app/node_modules
    # # Allows you to run container in detached mode.
    # stdin_open: true
    # tty: true
  server:
    # Telling docker-compose to build the client image using the Dockerfile in the server directory.
    build: ./back-end
    container_name: back_end_C
    ports:
      - "3001:3001"
    # volumes:
    #   - ./server:/app
    #   - ./app/node_modules